apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentserv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rentserv
  template:
    metadata:
      labels:
        app: rentserv
    spec:
      containers:
        - name: rentserv
          image: gcr.io/$GCP_PROJECT_ID/rentserv-$SCOPE:$SEMAPHORE_WORKFLOW_ID
          env:
            - name: NODE_ENV
              value: "production"

---

apiVersion: v1
kind: Service
metadata:
  name: rentserv
spec:
  selector:
    app: rentserv
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000